# Generated by Django 5.2.3 on 2025-07-10 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialize', '0002_tweet_likes_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='likes',
            new_name='like',
        ),
    ]
