# Generated by Django 5.2.3 on 2025-07-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialize', '0003_rename_likes_tweet_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='share_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
